In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [7]:
df= pd.read_excel("Rheumatic and Autoimmune Disease Dataset.xlsx")
df.head(5)

,Age,Gender,ESR,CRP,RF,Anti-CCP,HLA-B27,ANA,Anti-Ro,Anti-La,Anti-dsDNA,Anti-Sm,C3,C4,Disease
0,70,Male,39.0,18.6,34.2,29.9,Positive,Negative,Positive,Negative,Positive,Positive,NaN,27.0,Rheumatoid Arthritis
1,39,Female,26.0,21.7,35.5,28.9,Negative,NaN,Positive,NaN,Positive,NaN,100.0,66.0,Rheumatoid Arthritis
2,36,Female,41.0,15.6,21.3,21.3,Negative,Negative,NaN,Positive,Negative,NaN,158.0,12.0,Rheumatoid Arthritis
3,35,Male,43.0,23.4,26.0,39.0,NaN,NaN,Positive,Positive,NaN,NaN,119.0,41.0,Rheumatoid Arthritis
4,37,Female,30.0,NaN,38.1,30.8,Positive,Negative,Positive,Negative,Positive,Negative,144.0,49.0,Rheumatoid Arthritis

In [10]:
random_rows = df.sample(n=10)
random_rows

,Age,Gender,ESR,CRP,RF,Anti-CCP,HLA-B27,ANA,Anti-Ro,Anti-La,Anti-dsDNA,Anti-Sm,C3,C4,Disease
11475,37,Male,40.0,NaN,11.3,19.9,Negative,Positive,Negative,Positive,Positive,Negative,96.0,NaN,Psoriatic Arthritis
2725,22,Female,37.0,17.7,23.4,NaN,Negative,NaN,Negative,Positive,Negative,Positive,NaN,70.0,Rheumatoid Arthritis
6276,46,Male,13.0,1.4,14.9,33.4,NaN,Positive,Positive,NaN,NaN,NaN,122.0,48.0,Sjögren's Syndrome
9542,20,Female,NaN,NaN,12.8,10.9,Positive,Negative,Negative,Positive,Positive,NaN,123.0,43.0,Normal
7431,68,Female,15.0,1.8,9.6,26.5,Positive,Positive,Negative,NaN,Positive,NaN,60.0,5.0,Systemic Lupus Erythematosus
4240,31,Female,31.0,29.6,25.4,23.6,Positive,Negative,Positive,NaN,Positive,NaN,NaN,71.0,Ankylosing Spondylitis
846,42,Male,32.0,20.5,24.8,NaN,Negative,NaN,Negative,Positive,Positive,Positive,112.0,54.0,Rheumatoid Arthritis
7126,63,Male,3.0,1.1,NaN,NaN,Negative,Positive,Positive,Positive,Negative,NaN,NaN,38.0,Sjögren's Syndrome
624,42,Female,31.0,29.6,35.0,29.5,Negative,Negative,Negative,Positive,Negative,Positive,127.0,64.0,Rheumatoid Arthritis
7039,21,Female,18.0,0.4,NaN,14.8,Positive,Positive,Positive,NaN,Positive,NaN,191.0,52.0,Sjögren's Syndrome

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12085 entries, 0 to 12084
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         12085 non-null  int64
 1   Gender      12085 non-null  object
 2   ESR         10997 non-null  float64
 3   CRP         9668 non-null   float64
 4   RF          10756 non-null  float64
 5   Anti-CCP    8822 non-null   float64
 6   HLA-B27     10151 non-null  object
 7   ANA         8339 non-null   object
 8   Anti-Ro     9185 non-null   object
 9   Anti-La     9064 non-null   object
 10  Anti-dsDNA  7372 non-null   object
 11  Anti-Sm     6888 non-null   object
 12  C3          10393 non-null  float64
 13  C4          10031 non-null  float64
 14  Disease     12085 non-null  object
dtypes: float64(6), int64(1), object(8)
memory usage: 1.4+ MB

In [12]:
df.shape

(12085, 15)

In [13]:
!pip install summarytools
from summarytools import dfSummary
dfSummary(df)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: summarytools in c:\users\anjan\appdata\roaming\python\python313\site-packages (0.4.0)
Requirement already satisfied: pandas>=1.4.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from summarytools) (2.3.0)
Requirement already satisfied: ipython>=7.20.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from summarytools) (9.17.1)
Requirement already satisfied: numpy>=1.18.5 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from summarytools) (2.3.0)
Requirement already satisfied: matplotlib>=3.3.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from summarytools) (3.10.3)
Requirement already satisfied: jinja2>=3.1 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from summarytools) (3.1.6)
Requirement already satisfied: colorama>=0.4.4 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (3.0.53)
Requirement already satisfied: psutil>=7 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from ipython>=7.20.0->summarytools) (5.16.1)
Requirement already satisfied: wcwidth>=0.1.4 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.20.0->summarytools) (0.8.3)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from jedi>=0.18.2->ipython>=7.20.0->summarytools) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from jinja2>=3.1->summarytools) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (4.58.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->summarytools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from pandas>=1.4.0->summarytools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from pandas>=1.4.0->summarytools) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->summarytools) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.20.0->summarytools) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\anjan\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.20.0->summarytools) (3.0.2)
Requirement already satisfied: pure-eval in c:\users\anjan\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.20.0->summarytools) (0.2.4)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip